apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: ops-elasticsearch-maintenance
spec:
  schedule: 40 7 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ops-elasticsearch-maintenance
            image: quay.io/alliander/ops-elasticsearch-maintenance:5.4.1
            args:
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: ops-elasticsearch-maintenance-config
          restartPolicy: OnFailure
