apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {appName}
spec:
  schedule: 40 7 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {appName}
            image: {image}
            args:
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: {appName}
          restartPolicy: OnFailure
